# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

install: pip install -r requirements.txt

script: "nosetests --with-coverage --cover-package=basic_zappa_project"