# Config file for automatic testing at travis-ci.org

language: python

python:
  - 2.7
  - 3.5
  - 3.6

addons:
  postgresql: "9.4"

install: pip install -r requirements.txt

before_script:
  - psql -c 'create database zappa_boilerplate_test;' -U postgres

script: "nosetests --with-coverage --cover-package=zappa_boilerplate"

after_success:
  coveralls